platform :ios,'8.0'

target 'FastDemo' do
pod 'TZImagePickerController'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'Masonry'
pod 'Realm'
pod 'YYWebImage'
pod 'YYModel'
pod 'YYText'

pod 'MMKV'
pod 'HUPhotoBrowser'

end
